export interface DriverDayInfo {
    id_: string;
    driverName: string;
    driverId: string;
    date: string;
    activeHours: number;
    fuelConsumed: number;
    distanceTraveled: number;
    status: string;
}

function getToday(): string {
    return new Date().toISOString().split("T")[0];
}

export const mockDriverDayData: DriverDayInfo[] = [
    {
        id_: "DRV-001",
        driverName: "Juan Dela Cruz",
        driverId: "DRV-001",
        date: getToday(),
        activeHours: 7.5,
        fuelConsumed: 14.2,
        distanceTraveled: 92.3,
        status: "ACTIVE",
    },
    {
        id_: "DRV-002",
        driverName: "Leon S. Kennedy",
        driverId: "DRV-002",
        date: getToday(),
        activeHours: 6.0,
        fuelConsumed: 11.8,
        distanceTraveled: 78.6,
        status: "ACTIVE",
    },
    {
        id_: "DRV-003",
        driverName: "Chris Redfield",
        driverId: "DRV-003",
        date: getToday(),
        activeHours: 2.0,
        fuelConsumed: 3.4,
        distanceTraveled: 40.6,
        status: "ACTIVE",
    },
    {
        id_: "DRV-004",
        driverName: "John Doe",
        driverId: "DRV-004",
        date: getToday(),
        activeHours: 7.8,
        fuelConsumed: 23.4,
        distanceTraveled: 176.6,
        status: "ACTIVE",
    },
    {
        id_: "DRV-005",
        driverName: "John Smith",
        driverId: "DRV-005",
        date: getToday(),
        activeHours: 4.9,
        fuelConsumed: 7.4,
        distanceTraveled: 55.8,
        status: "ACTIVE",
    },
    {
        id_: "DRV-006",
        driverName: "Jane Doe",
        driverId: "DRV-006",
        date: getToday(),
        activeHours: 7.4,
        fuelConsumed: 12.6,
        distanceTraveled: 82.9,
        status: "ACTIVE",
    },
    {
        id_: "DRV-007",
        driverName: "Sisyphus",
        driverId: "DRV-007",
        date: getToday(),
        activeHours: 8.0,
        fuelConsumed: 0.0,
        distanceTraveled: 99999,
        status: "FULLY UTILIZED",
    },
    {
        id_: "DRV-008",
        driverName: "Jill Valentine",
        driverId: "DRV-008",
        date: getToday(),
        activeHours: 6.8,
        fuelConsumed: 13.1,
        distanceTraveled: 88.4,
        status: "ACTIVE",
    },
    {
        id_: "DRV-009",
        driverName: "Claire Redfield",
        driverId: "DRV-009",
        date: getToday(),
        activeHours: 5.2,
        fuelConsumed: 9.5,
        distanceTraveled: 61.3,
        status: "ACTIVE",
    },
    {
        id_: "DRV-010",
        driverName: "Ethan Winters",
        driverId: "DRV-010",
        date: getToday(),
        activeHours: 3.5,
        fuelConsumed: 6.2,
        distanceTraveled: 42.7,
        status: "INACTIVE",
    },
    {
        id_: "DRV-011",
        driverName: "Ada Wong",
        driverId: "DRV-011",
        date: getToday(),
        activeHours: 1.2,
        fuelConsumed: 2.1,
        distanceTraveled: 15.8,
        status: "ACTIVE",
    },
    {
        id_: "DRV-012",
        driverName: "Barry Burton",
        driverId: "DRV-012",
        date: getToday(),
        activeHours: 7.1,
        fuelConsumed: 14.8,
        distanceTraveled: 95.2,
        status: "ACTIVE",
    },
    {
        id_: "DRV-013",
        driverName: "Rebecca Chambers",
        driverId: "DRV-013",
        date: getToday(),
        activeHours: 4.6,
        fuelConsumed: 8.3,
        distanceTraveled: 58.9,
        status: "ACTIVE",
    },
    {
        id_: "DRV-014",
        driverName: "Albert Wesker",
        driverId: "DRV-014",
        date: getToday(),
        activeHours: 9.0,
        fuelConsumed: 18.7,
        distanceTraveled: 120.5,
        status: "FULLY UTILIZED",
    },
    {
        id_: "DRV-015",
        driverName: "Mr. Bean",
        driverId: "DRV-015",
        date: getToday(),
        activeHours: 6.3,
        fuelConsumed: 11.0,
        distanceTraveled: 74.6,
        status: "ACTIVE",
    },
];
