import type { Vehicle } from "@/lib/types/vehicle";

export const mockVehicleData: Vehicle[] = [
    {
        id_: "VH-001",
        vehicleId_: "VH-001",
        lastDriver: "Juan Dela Cruz",
        driverId: "DRV-001",
        vehicleType: "Van",
        plateNumber: "ABC-1001",
        weightCapacity: 1500,
        target: 1000,
        status: "EN ROUTE",
        vehicleMaker: "Toyota",
        vehicleModel: "Hiace",
        initOdometer: 15234,
        year: 2022,
        lastModified: "2026-08-04T09:30:00",
    },
    {
        id_: "VH-002",
        vehicleId_: "VH-002",
        lastDriver: "Leon S. Kennedy",
        driverId: "DRV-002",
        vehicleType: "Motorcycle",
        plateNumber: "ABC-1002",
        weightCapacity: 100,
        target: 1000,
        status: "STANDBY",
        vehicleMaker: "Honda",
        vehicleModel: "Click 125",
        initOdometer: 8921,
        year: 2023,
        lastModified: "2026-08-03T14:15:00",
    },
    {
        id_: "VH-003",
        vehicleId_: "VH-003",
        lastDriver: "Chris Redfield",
        driverId: "DRV-003",
        vehicleType: "Car",
        plateNumber: "ABC-1003",
        weightCapacity: 500,
        target: 1000,
        status: "EN ROUTE",
        vehicleMaker: "Toyota",
        vehicleModel: "Vios",
        initOdometer: 24100,
        year: 2021,
        lastModified: "2026-08-02T10:45:00",
    },
    {
        id_: "VH-004",
        vehicleId_: "VH-004",
        lastDriver: "John Doe",
        driverId: "DRV-004",
        vehicleType: "Van",
        plateNumber: "ABC-1004",
        weightCapacity: 1800,
        target: 1000,
        status: "STANDBY",
        vehicleMaker: "Nissan",
        vehicleModel: "Urvan",
        initOdometer: 18765,
        year: 2022,
        lastModified: "2026-08-01T16:20:00",
    },
    {
        id_: "VH-005",
        vehicleId_: "VH-005",
        lastDriver: "John Smith",
        driverId: "DRV-005",
        vehicleType: "Motorcycle",
        plateNumber: "ABC-1005",
        weightCapacity: 80,
        target: 1000,
        status: "INACTIVE",
        vehicleMaker: "Yamaha",
        vehicleModel: "NMAX",
        initOdometer: 31200,
        year: 2020,
        lastModified: "2026-07-31T08:05:00",
    },
    {
        id_: "VH-006",
        vehicleId_: "VH-006",
        lastDriver: "Jane Doe",
        driverId: "DRV-006",
        vehicleType: "Car",
        plateNumber: "ABC-1006",
        weightCapacity: 600,
        target: 1000,
        status: "STANDBY",
        vehicleMaker: "Honda",
        vehicleModel: "Civic",
        initOdometer: 9800,
        year: 2023,
        lastModified: "2026-07-30T11:50:00",
    },
    {
        id_: "VH-007",
        vehicleId_: "VH-007",
        lastDriver: "Sisyphus",
        driverId: "DRV-007",
        vehicleType: "Van",
        plateNumber: "ABC-1007",
        weightCapacity: 2000,
        target: 1000,
        status: "EN ROUTE",
        vehicleMaker: "Toyota",
        vehicleModel: "Hilux",
        initOdometer: 45000,
        year: 2019,
        lastModified: "2026-07-29T15:35:00",
    },
    {
        id_: "VH-008",
        vehicleId_: "VH-008",
        lastDriver: "Jill Valentine",
        driverId: "DRV-008",
        vehicleType: "Car",
        plateNumber: "ABC-1008",
        weightCapacity: 450,
        target: 1000,
        status: "STANDBY",
        vehicleMaker: "Mitsubishi",
        vehicleModel: "Mirage",
        initOdometer: 5600,
        year: 2024,
        lastModified: "2026-07-28T09:10:00",
    },
    {
        id_: "VH-009",
        vehicleId_: "VH-009",
        lastDriver: "Claire Redfield",
        driverId: "DRV-009",
        vehicleType: "Motorcycle",
        plateNumber: "ABC-1009",
        weightCapacity: 120,
        target: 1000,
        status: "EN ROUTE",
        vehicleMaker: "Suzuki",
        vehicleModel: "Raider 150",
        initOdometer: 12500,
        year: 2021,
        lastModified: "2026-07-27T13:40:00",
    },
    {
        id_: "VH-010",
        vehicleId_: "VH-010",
        lastDriver: "Ethan Winters",
        driverId: "DRV-010",
        vehicleType: "Car",
        plateNumber: "ABC-1010",
        weightCapacity: 550,
        target: 1000,
        status: "INACTIVE",
        vehicleMaker: "Ford",
        vehicleModel: "Escape",
        initOdometer: 67000,
        year: 2018,
        lastModified: "2026-07-26T10:25:00",
    },
    {
        id_: "VH-011",
        vehicleId_: "VH-011",
        lastDriver: "Ada Wong",
        driverId: "DRV-011",
        vehicleType: "Motorcycle",
        plateNumber: "ABC-1011",
        weightCapacity: 90,
        target: 1000,
        status: "STANDBY",
        vehicleMaker: "Honda",
        vehicleModel: "PCX 160",
        initOdometer: 4100,
        year: 2024,
        lastModified: "2026-07-25T17:55:00",
    },
    {
        id_: "VH-012",
        vehicleId_: "VH-012",
        lastDriver: "Barry Burton",
        driverId: "DRV-012",
        vehicleType: "Van",
        plateNumber: "ABC-1012",
        weightCapacity: 1600,
        target: 1000,
        status: "ACTIVE",
        vehicleMaker: "Toyota",
        vehicleModel: "Innova",
        initOdometer: 28000,
        year: 2020,
        lastModified: "2026-07-24T12:30:00",
    },
    {
        id_: "VH-013",
        vehicleId_: "VH-013",
        lastDriver: "Rebecca Chambers",
        driverId: "DRV-013",
        vehicleType: "Car",
        plateNumber: "ABC-1013",
        weightCapacity: 400,
        target: 1000,
        status: "EN ROUTE",
        vehicleMaker: "Hyundai",
        vehicleModel: "Accent",
        initOdometer: 18200,
        year: 2022,
        lastModified: "2026-07-23T09:45:00",
    },
    {
        id_: "VH-014",
        vehicleId_: "VH-014",
        lastDriver: "Albert Wesker",
        driverId: "DRV-014",
        vehicleType: "Van",
        plateNumber: "ABC-1014",
        weightCapacity: 1200,
        target: 1000,
        status: "RESERVED",
        vehicleMaker: "Nissan",
        vehicleModel: "NV350",
        initOdometer: 7500,
        year: 2023,
        lastModified: "2026-07-22T14:00:00",
    },
    {
        id_: "VH-015",
        vehicleId_: "VH-015",
        lastDriver: "Mr. Bean",
        driverId: "DRV-015",
        vehicleType: "Motorcycle",
        plateNumber: "ABC-1015",
        weightCapacity: 70,
        target: 1000,
        status: "STANDBY",
        vehicleMaker: "Yamaha",
        vehicleModel: "Mio Sporty",
        initOdometer: 22000,
        year: 2019,
        lastModified: "2026-07-21T11:15:00",
    },
    {
        id_: "VH-016",
        vehicleId_: "VH-016",
        lastDriver: "",
        driverId: "",
        vehicleType: "Car",
        plateNumber: "ABC-1016",
        weightCapacity: 400,
        target: 1000,
        status: "INACTIVE",
        vehicleMaker: "Toyota",
        vehicleModel: "Wigo",
        initOdometer: 5000,
        year: 2024,
        lastModified: "2026-07-20T16:50:00",
    },
];
